name: Docker Build & Push Simapp (main)
# Build & Push builds the simapp docker image on every push to main and
# and pushes the image to https://ghcr.io/cosmos/ibc-go-simd
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker.yml'
      - '**.go'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ibc-go-simd

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176
      with:
        images: ${{ env.REGISTRY }}/cosmos/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: |
          IBC_GO_VERSION=main
