# This workflow is added in order for the required e2e/build job to run successfully even
# when the PR targets non-code files (e.g. docs, LICENSE, etc). This is done because of the
# way Github required checks work, reference:
#
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Tests / E2E
on:
  workflow_dispatch:
  pull_request:
    types:
      # trigger workflow if PR is opened directly as R4R.
      - opened
      # trigger workflow if changes are pushed to the branch.
      - synchronize
      # trigger workflow if PR is marked ready for review.
      - ready_for_review
    paths:
      - "docs/**"
      - "**.md"
      - "LICENSE"

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - run: echo "E2E tests skipped for docs."